export type AutomationSchedulePolicy={kind:"one_shot";at:string}|{kind:"interval";every_minutes:number;anchor:string}|{kind:"daily";timezone:string;local_time:string;missed_policy:"catch_up"|"skip"};
export function nextAutomationOccurrence(policy:AutomationSchedulePolicy,input:{after:string;last_scheduled_at?:string}):string|undefined{const after=Date.parse(input.after);if(policy.kind==="one_shot")return Date.parse(policy.at)>after?new Date(policy.at).toISOString():undefined;if(policy.kind==="interval"){const anchor=Date.parse(policy.anchor),step=policy.every_minutes*60000;if(step<=0)throw new Error("automation_interval_invalid");const index=Math.max(1,Math.floor((after-anchor)/step)+1);return new Date(anchor+index*step).toISOString()}validateZone(policy.timezone);const[targetHour,targetMinute]=parseTime(policy.local_time);const base=input.last_scheduled_at?addLocalDays(localParts(input.last_scheduled_at,policy.timezone).date,1):localParts(input.after,policy.timezone).date;for(let day=0;day<370;day++){const date=addLocalDays(base,day),candidates=findLocalInstants(date,targetHour,targetMinute,policy.timezone);const chosen=candidates.find(ms=>ms>after);if(chosen!==undefined)return new Date(chosen).toISOString();if(candidates.length===0){const shifted=findFirstLocalInstantAfter(date,targetHour,targetMinute,policy.timezone);if(shifted!==undefined&&shifted>after)return new Date(shifted).toISOString()}}throw new Error("automation_schedule_unresolvable")}
export function recoverMissedAutomationOccurrences(policy:AutomationSchedulePolicy,input:{last_scheduled_at:string;now:string;paused?:boolean;max_catch_up?:number}):string[]{if(input.paused)return[];const next=nextAutomationOccurrence(policy,{after:input.last_scheduled_at,last_scheduled_at:input.last_scheduled_at});if(!next||Date.parse(next)>Date.parse(input.now))return[];if(policy.kind==="daily"&&policy.missed_policy==="skip")return[nextAutomationOccurrence(policy,{after:input.now})].filter((x):x is string=>Boolean(x));const result:string[]=[];let cursor=input.last_scheduled_at;for(let i=0;i<(input.max_catch_up??100);i++){const occurrence=nextAutomationOccurrence(policy,{after:cursor,last_scheduled_at:cursor});if(!occurrence||Date.parse(occurrence)>Date.parse(input.now))break;result.push(occurrence);cursor=occurrence}return result}
export function automationNeedsAgent(kind:string):boolean{return!["wiki_reindex","skill_curator","learning_evaluation","memory_review"].includes(kind)}
function validateZone(zone:string){new Intl.DateTimeFormat("en-US",{timeZone:zone}).format(new Date())}function parseTime(value:string):[number,number]{const match=value.match(/^([01]\d|2[0-3]):([0-5]\d)$/);if(!match)throw new Error("automation_local_time_invalid");return[Number(match[1]),Number(match[2])]}
function localParts(value:string,zone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));const get=(type:string)=>Number(parts.find(x=>x.type===type)?.value);return{date:`${get("year")}-${String(get("month")).padStart(2,"0")}-${String(get("day")).padStart(2,"0")}`,hour:get("hour"),minute:get("minute")}}
function addLocalDays(date:string,days:number){const[y,m,d]=date.split("-").map(Number),next=new Date(Date.UTC(y!,m!-1,d!+days));return`${next.getUTCFullYear()}-${String(next.getUTCMonth()+1).padStart(2,"0")}-${String(next.getUTCDate()).padStart(2,"0")}`}
function findLocalInstants(date:string,hour:number,minute:number,zone:string){const[y,m,d]=date.split("-").map(Number),guess=Date.UTC(y!,m!-1,d!,hour,minute),found:number[]=[];for(let ms=guess-18*3600000;ms<=guess+18*3600000;ms+=60000){const p=localParts(new Date(ms).toISOString(),zone);if(p.date===date&&p.hour===hour&&p.minute===minute)found.push(ms)}return found}
function findFirstLocalInstantAfter(date:string,hour:number,minute:number,zone:string){const[y,m,d]=date.split("-").map(Number),guess=Date.UTC(y!,m!-1,d!,hour,minute),target=hour*60+minute;for(let ms=guess-18*3600000;ms<=guess+18*3600000;ms+=60000){const p=localParts(new Date(ms).toISOString(),zone);if(p.date===date&&p.hour*60+p.minute>target)return ms}return undefined}
