import type { JsonColumn } from "./json-column";

export interface ExternalSendsTable { id: string; channel: string; status: string; target_json: JsonColumn; title: string; body: string; operation_id: string | null; approval_request_id: string | null; dispatch_result_json: JsonColumn | null; created_at: string; updated_at: string; dispatched_at: string | null; dispatch_claim_token: string | null; dispatch_claimed_at: string | null; dispatch_lease_until: string | null; }
export interface GatewayPairingsTable { id: string; channel: string; source_identity: string; source_label: string; status: string; pairing_code: string | null; session_key: string; metadata_json: JsonColumn; requested_at: string; expires_at: string | null; resolved_at: string | null; updated_at: string; }
export interface GatewayPairingPoliciesTable { id: string; channel: string; status: string; trust_mode: string; allowlist_json: JsonColumn; allowed_tools_json: JsonColumn; pairing_ttl_ms: number | null; duplicate_window_ms: number | null; rate_limit_window_ms: number | null; rate_limit_max: number | null; metadata_json: JsonColumn; created_at: string; updated_at: string; }
export interface GatewayRoutingPoliciesTable { id: string; channel: string; status: string; session_key_strategy: string; default_account_id: string | null; default_thread_id: string | null; default_route: string; metadata_json: JsonColumn; created_at: string; updated_at: string; }
export interface GatewayInboundMessagesTable { id: string; channel: string; source_identity: string; body: string; status: string; trusted: number; session_key: string | null; pairing_id: string | null; message_id: string | null; error: string | null; metadata_json: JsonColumn; created_at: string; updated_at: string; }
export interface GatewayDeliveriesTable { id: string; inbound_id: string | null; session_key: string; channel: string; status: string; idempotency_key: string; payload_json: JsonColumn; attempt: number; max_attempts: number; next_attempt_at: string | null; lease_until: string | null; receipt_json: JsonColumn | null; last_error: string | null; created_at: string; updated_at: string; delivered_at: string | null; }
export interface GatewayBoundaryPoliciesTable { id: string; source_channel: string; source_identity: string | null; session_key: string; allowed_tools_json: JsonColumn; mcp_config_refs_json: JsonColumn; secret_refs_json: JsonColumn; sandbox_json: JsonColumn; path_normalization_json: JsonColumn; allowlist_json: JsonColumn; timeout_ms: number | null; concurrency_lock_json: JsonColumn | null; metadata_json: JsonColumn; created_at: string; updated_at: string; }
export interface GatewayMcpConfigsTable { id: string; server_name: string; transport: string; enabled: number; allowed_tools_json: JsonColumn; config_ref_json: JsonColumn | null; secret_refs_json: JsonColumn; stdio_json: JsonColumn | null; http_json: JsonColumn | null; metadata_json: JsonColumn; created_at: string; updated_at: string; }
export interface GatewayConcurrencyLocksTable { id: string; lock_key: string; scope: string; policy_id: string | null; owner_ref_json: JsonColumn | null; status: string; acquired_at: string; expires_at: string; released_at: string | null; metadata_json: JsonColumn; }
export interface GatewaySandboxInstancesTable { id: string; instance_key: string; scope: string; backend: string; status: string; sandbox_json: JsonColumn; session_key: string | null; owner_ref_json: JsonColumn | null; workspace_root: string | null; created_at: string; updated_at: string; last_used_at: string | null; deleted_at: string | null; metadata_json: JsonColumn; }
export interface GatewaySandboxWorkspaceSyncsTable { id: string; instance_id: string; instance_key: string; direction: string; status: string; workspace_root: string | null; remote_workspace_root: string | null; file_count: number | null; byte_count: number | null; error: string | null; started_at: string; completed_at: string | null; metadata_json: JsonColumn; }
