import type { JsonColumn } from "./json-column";

export interface LearningResourceUseTable { id: string; run_id: string; session_id: string; resource_kind: string; resource_id: string; resource_version: string | null; content_hash: string | null; stage: string; source_operation_id: string | null; metadata_json: JsonColumn; created_at: string; }
export interface LearningEvaluationTable { id: string; learning_resource_ref_json: JsonColumn; learning_resource_version: string | null; task_class: string; compared_run_ids_json: JsonColumn; before_metrics_json: JsonColumn; after_metrics_json: JsonColumn; effect_estimate: number; confidence: number; assessment: string; evidence_refs_json: JsonColumn; evaluator: string; created_at: string; }
export interface LearningSnapshotTable { id: string; run_id: string; path: string; resource_counts_json: JsonColumn; created_at: string; restored_at: string | null; }
export interface BackgroundReviewChangeTable { id: string; origin: string; source_run_id: string; source_session_id: string; review_run_id: string; mutation_kind: string; resource_ref_json: JsonColumn; before_version: string | null; after_version: string; reason_summary: string; evidence_refs_json: JsonColumn; created_at: string; }
export interface LearningJobReportTable { id: string; job_kind: string; run_id: string; report_json: JsonColumn; created_at: string; }
export interface CuratorStateTable { id: string; paused: number; interval_hours: number; min_idle_hours: number; stale_after_days: number; archive_after_days: number; last_run_at: string | null; last_run_summary: string | null; run_count: number; updated_at: string; }
export interface ReflectionRunsTable { id: string; kind: string; source_run_id: string | null; session_id: string | null; status: string; input_summary: string; output_summary: string | null; started_at: string; completed_at: string | null; error: string | null; }
export interface ReflectionSuggestionsTable { id: string; reflection_run_id: string; suggestion_type: string; status: string; title: string; content: string; target_ref_json: JsonColumn | null; source_refs_json: JsonColumn; confidence: number; created_at: string; updated_at: string; }
export interface ExternalAssistRecordsTable { id: string; phase: string; status: string; provider_id: string; session_id: string; run_id: string | null; input_message_id: string | null; query: string; role: string; hints_json: JsonColumn; error: string | null; isolated_from_memory: number; included_in_active_memory: number; created_at: string; updated_at: string; }
