import type { JsonColumn } from "./json-column";

export interface SessionsTable { id: string; session_key: string; room_id: string | null; title: string; ui_locale: string; output_locale: string; created_at: string; updated_at: string; }
export interface MessagesTable { id: string; session_id: string; role: "user" | "agent" | "system"; content: string; input_locale: string; output_locale: string; envelope_json: JsonColumn | null; created_at: string; }
export interface MessagePresentationsTable { id: string; session_id: string; message_id: string; kind: string; title: string; subtitle: string; collection_id: string; view_id: string; renderer: string; view_state_json: JsonColumn | null; surface_id: string | null; revision_id: string | null; preview_url: string | null; created_at: string; updated_at: string; }
export interface OperationsTable { id: string; session_id: string | null; run_id: string | null; capability_id: string; operation: string; actor_identity: string; participant_id: string | null; participant_kind: string | null; requested_by_participant_id: string | null; room_id: string | null; principal_json: JsonColumn | null; source_json: JsonColumn | null; session_ref_json: JsonColumn | null; instruction_source: string; instruction_authority: string; channel: string; input_hash: string; input_ref_json: JsonColumn | null; target_resource_refs_json: JsonColumn; proposed_effects_json: JsonColumn; status: string; policy_decision_id: string | null; approval_request_id: string | null; result_ref_json: JsonColumn | null; error: string | null; correlation_id: string | null; created_at: string; updated_at: string; }
export interface BackendRunsTable { id: string; session_id: string | null; room_id: string | null; principal_json: JsonColumn | null; source_json: JsonColumn | null; session_ref_json: JsonColumn | null; agent_id: string | null; requested_by_participant_id: string | null; input_message_id: string | null; output_message_id: string | null; backend_id: string; backend_kind: string; backend_session_id: string | null; status: string; phase: string | null; current_attempt: number | null; request_idempotency_key: string | null; request_hash: string | null; started_at: string; completed_at: string | null; input_summary: string; output_summary: string | null; error_code: string | null; metadata_json: JsonColumn; }
export interface SessionRunReservationsTable { session_id: string; run_id: string; status: string; version: number; held_at: string; released_at: string | null; }
export interface RunLeasesTable { lane_key: string; run_id: string; status: string; version: number; held_at: string; released_at: string | null; }
export interface BackendEventsTable { id: string; run_id: string; session_id: string | null; backend_session_id: string | null; event_type: string; sequence: number; attempt_no: number | null; source_event_id: string | null; source_sequence: number | null; payload_json: JsonColumn; resource_refs_json: JsonColumn; created_at: string; }
export interface ToolRunsTable { id: string; run_id: string; session_id: string | null; tool_call_id: string | null; provider_tool_name: string; action_id: string | null; status: string; input_summary: string; output_summary: string; error_code: string | null; resource_refs_json: JsonColumn; created_at: string; }
export interface WorkspaceChangesTable { id: string; run_id: string | null; session_id: string | null; room_id: string | null; activity_id: string | null; domain_operation_id: string | null; session_ref_json: JsonColumn | null; resource_ref_json: JsonColumn; change_type: string; summary: string; legacy_operation_id: string | null; correlation_id: string | null; created_at: string; }
