import { stableHash, type ResourceRef } from "@samurai-agent/core-schemas";

export interface CuratorResourceCandidate { ref:ResourceRef; content:string; pinned:boolean; usage_count:number; success_rate:number; correction_rate:number; last_used_at?:string; source_trust:number; supersedes?:string[]; derived_from?:string[]; }
export interface CuratorGraphEdge { from_ref:ResourceRef;to_ref:ResourceRef;relation:"duplicate"|"overlaps"|"conflicts"|"supersedes"|"derived_from";confidence:number;evidence:string[]; }
export function buildCuratorResourceGraph(resources:CuratorResourceCandidate[]):CuratorGraphEdge[]{const edges:CuratorGraphEdge[]=[];for(let i=0;i<resources.length;i++)for(let j=i+1;j<resources.length;j++){const a=resources[i]!,b=resources[j]!;const relation=relationBetween(a,b);if(relation)edges.push({from_ref:a.ref,to_ref:b.ref,...relation})}for(const resource of resources){for(const id of resource.supersedes??[]){const target=resources.find(x=>x.ref.id===id);if(target)edges.push({from_ref:resource.ref,to_ref:target.ref,relation:"supersedes",confidence:1,evidence:["explicit_supersedes"]})}for(const id of resource.derived_from??[]){const target=resources.find(x=>x.ref.id===id);if(target)edges.push({from_ref:resource.ref,to_ref:target.ref,relation:"derived_from",confidence:1,evidence:["explicit_derived_from"]})}}return dedupe(edges)}
export function curatorLifecycleDecision(resource:CuratorResourceCandidate,input:{now:string;stale_days:number;archive_days:number}){if(resource.pinned)return{decision:"keep"as const,reason:"owner_pinned"};const age=resource.last_used_at?Math.max(0,(Date.parse(input.now)-Date.parse(resource.last_used_at))/86400000):Infinity;if(resource.correction_rate>.35)return{decision:"review"as const,reason:"high_correction_rate"};if(resource.usage_count===0&&age>=input.archive_days&&resource.source_trust<.8)return{decision:"archive"as const,reason:"unused_untrusted_archive_threshold"};if(age>=input.stale_days)return{decision:"stale"as const,reason:"stale_threshold"};return{decision:"keep"as const,reason:resource.success_rate>=.8?"successful_usage":"recent_or_used"}}
export function curatorEdgeId(edge:CuratorGraphEdge){return`learning_edge_${stableHash({from:edge.from_ref.id,to:edge.to_ref.id,relation:edge.relation})}`}
function relationBetween(a:CuratorResourceCandidate,b:CuratorResourceCandidate){const na=normalize(a.content),nb=normalize(b.content);if(na===nb)return{relation:"duplicate"as const,confidence:1,evidence:["normalized_content_equal"]};const ta=tokens(na),tb=tokens(nb),intersection=[...ta].filter(x=>tb.has(x)).length,union=new Set([...ta,...tb]).size,similarity=union?intersection/union:0;if(similarity>=.45&&opposite(na,nb))return{relation:"conflicts"as const,confidence:Number(Math.min(.95,.6+similarity*.3).toFixed(3)),evidence:[`token_similarity:${similarity.toFixed(3)}`,"opposite_directive"]};if(similarity>=.55)return{relation:"overlaps"as const,confidence:Number(similarity.toFixed(3)),evidence:[`token_similarity:${similarity.toFixed(3)}`]};return undefined}
function normalize(x:string){return x.normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim()}function tokens(x:string){return new Set(x.match(/[a-z0-9]+|[\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Han}]{2,}/gu)??[])}function opposite(a:string,b:string){const positive=/(必ず|許可|有効|must|allow|enable)/,negative=/(禁止|しない|無効|never|deny|disable)/;return positive.test(a)&&negative.test(b)||negative.test(a)&&positive.test(b)}function dedupe(edges:CuratorGraphEdge[]){const seen=new Set<string>();return edges.filter(e=>{const key=`${e.from_ref.id}:${e.to_ref.id}:${e.relation}`;if(seen.has(key))return false;seen.add(key);return true})}
