import type { WorkspaceMigration } from "../kernel/migration-runner";

// Keep this list byte-for-byte compatible with the historical v1 checksum.
const statements = [
  `CREATE TABLE IF NOT EXISTS sessions (
        id TEXT PRIMARY KEY,
        session_key TEXT NOT NULL,
        title TEXT NOT NULL,
        ui_locale TEXT NOT NULL,
        output_locale TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS messages (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        input_locale TEXT NOT NULL,
        output_locale TEXT NOT NULL,
        envelope_json TEXT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE TABLE IF NOT EXISTS message_presentations (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL,
        message_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        title TEXT NOT NULL,
        subtitle TEXT NOT NULL,
        collection_id TEXT NOT NULL,
        view_id TEXT NOT NULL,
        renderer TEXT NOT NULL,
        view_state_json TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (session_id) REFERENCES sessions(id),
        FOREIGN KEY (message_id) REFERENCES messages(id)
      )`,
  `CREATE INDEX IF NOT EXISTS idx_message_presentations_session_message ON message_presentations(session_id, message_id)`,
  `CREATE TABLE IF NOT EXISTS operations (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL,
        capability_id TEXT NOT NULL,
        operation TEXT NOT NULL,
        actor_identity TEXT NOT NULL,
        instruction_source TEXT NOT NULL,
        instruction_authority TEXT NOT NULL,
        channel TEXT NOT NULL,
        input_hash TEXT NOT NULL,
        input_ref_json TEXT,
        target_resource_refs_json TEXT NOT NULL,
        proposed_effects_json TEXT NOT NULL,
        status TEXT NOT NULL,
        policy_decision_id TEXT,
        approval_request_id TEXT,
        result_ref_json TEXT,
        error TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE TABLE IF NOT EXISTS domain_command_executions (
        id TEXT PRIMARY KEY,
        idempotency_key TEXT NOT NULL UNIQUE,
        command_id TEXT NOT NULL,
        input_source TEXT NOT NULL,
        payload_hash TEXT NOT NULL,
        phase TEXT NOT NULL DEFAULT 'external_running',
        status TEXT NOT NULL,
        result_json TEXT,
        error TEXT,
        heartbeat_at TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE INDEX IF NOT EXISTS idx_domain_command_executions_status_updated ON domain_command_executions(status, updated_at)`,
  `CREATE TABLE IF NOT EXISTS objectives (
        id TEXT PRIMARY KEY,
        session_id TEXT,
        title TEXT NOT NULL,
        objective TEXT NOT NULL,
        completion_criteria_json TEXT NOT NULL,
        status TEXT NOT NULL,
        token_budget INTEGER,
        time_budget_ms INTEGER,
        max_attempts INTEGER,
        current_checkpoint_id TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        completed_at TEXT
      )`,
  `CREATE INDEX IF NOT EXISTS idx_objectives_status_updated ON objectives(status, updated_at)`,
  `CREATE TABLE IF NOT EXISTS work_items (
        id TEXT PRIMARY KEY,
        objective_id TEXT NOT NULL,
        parent_work_item_id TEXT,
        instruction TEXT NOT NULL,
        status TEXT NOT NULL,
        priority INTEGER NOT NULL,
        attempt INTEGER NOT NULL,
        max_attempts INTEGER NOT NULL,
        idempotency_key TEXT NOT NULL UNIQUE,
        lease_owner TEXT,
        lease_expires_at TEXT,
        heartbeat_at TEXT,
        retry_after_at TEXT,
        backend_run_id TEXT,
        current_checkpoint_id TEXT,
        failure_kind TEXT,
        error TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        started_at TEXT,
        completed_at TEXT,
        FOREIGN KEY (objective_id) REFERENCES objectives(id),
        FOREIGN KEY (parent_work_item_id) REFERENCES work_items(id)
      )`,
  `CREATE INDEX IF NOT EXISTS idx_work_items_claim ON work_items(status, retry_after_at, priority, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_work_items_objective ON work_items(objective_id, status)`,
  `CREATE TABLE IF NOT EXISTS work_dependencies (
        id TEXT PRIMARY KEY,
        objective_id TEXT NOT NULL,
        predecessor_work_item_id TEXT NOT NULL,
        successor_work_item_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(predecessor_work_item_id, successor_work_item_id),
        FOREIGN KEY (objective_id) REFERENCES objectives(id),
        FOREIGN KEY (predecessor_work_item_id) REFERENCES work_items(id),
        FOREIGN KEY (successor_work_item_id) REFERENCES work_items(id)
      )`,
  `CREATE INDEX IF NOT EXISTS idx_work_dependencies_successor ON work_dependencies(successor_work_item_id)`,
  `CREATE TABLE IF NOT EXISTS run_checkpoints (
        id TEXT PRIMARY KEY,
        objective_id TEXT NOT NULL,
        work_item_id TEXT NOT NULL,
        sequence INTEGER NOT NULL,
        phase TEXT NOT NULL,
        idempotency_key TEXT NOT NULL UNIQUE,
        backend_run_id TEXT,
        backend_session_id TEXT,
        event_cursor INTEGER,
        summary TEXT NOT NULL,
        generated_resource_refs_json TEXT NOT NULL,
        pending_operation_ids_json TEXT NOT NULL,
        state_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(work_item_id, sequence),
        FOREIGN KEY (objective_id) REFERENCES objectives(id),
        FOREIGN KEY (work_item_id) REFERENCES work_items(id)
      )`,
  `CREATE INDEX IF NOT EXISTS idx_run_checkpoints_work_item ON run_checkpoints(work_item_id, sequence)`,
  `CREATE TABLE IF NOT EXISTS workspace_file_transactions (
        id TEXT PRIMARY KEY,
        kind TEXT NOT NULL,
        status TEXT NOT NULL,
        target_path TEXT NOT NULL,
        staged_path TEXT NOT NULL,
        collection_id TEXT,
        record_id TEXT,
        patch_id TEXT,
        before_json TEXT NOT NULL,
        after_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE INDEX IF NOT EXISTS idx_workspace_file_transactions_status ON workspace_file_transactions(status, created_at)`,
  `CREATE TABLE IF NOT EXISTS generated_surfaces (
        id TEXT PRIMARY KEY,
        state TEXT NOT NULL,
        session_id TEXT NOT NULL,
        title TEXT NOT NULL,
        definition_json TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        current_revision_id TEXT NOT NULL,
        current_revision INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE TABLE IF NOT EXISTS artifact_revisions (
        id TEXT PRIMARY KEY,
        artifact_id TEXT NOT NULL,
        revision INTEGER NOT NULL,
        revision_json TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        file_path TEXT NOT NULL,
        blob_path TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(artifact_id, revision),
        FOREIGN KEY (artifact_id) REFERENCES artifacts(id)
      )`,
  `CREATE INDEX IF NOT EXISTS idx_artifact_revisions_artifact ON artifact_revisions(artifact_id, revision)`,
  `CREATE TABLE IF NOT EXISTS generated_surface_revisions (
        id TEXT PRIMARY KEY,
        surface_id TEXT NOT NULL,
        revision INTEGER NOT NULL,
        revision_json TEXT NOT NULL,
        bundle_hash TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(surface_id, revision),
        FOREIGN KEY (surface_id) REFERENCES generated_surfaces(id)
      )`,
  `CREATE INDEX IF NOT EXISTS idx_generated_surface_revisions_surface ON generated_surface_revisions(surface_id, revision)`,
  `CREATE TABLE IF NOT EXISTS surface_interactions (
        id TEXT PRIMARY KEY,
        surface_id TEXT NOT NULL,
        revision_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        interaction_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        FOREIGN KEY (surface_id) REFERENCES generated_surfaces(id),
        FOREIGN KEY (revision_id) REFERENCES generated_surface_revisions(id),
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE INDEX IF NOT EXISTS idx_surface_interactions_surface ON surface_interactions(surface_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS policy_decisions (
        id TEXT PRIMARY KEY,
        operation_id TEXT NOT NULL,
        capability_id TEXT NOT NULL,
        operation TEXT NOT NULL,
        decision TEXT NOT NULL,
        reason TEXT NOT NULL,
        policy_inputs_json TEXT NOT NULL,
        matched_rules_json TEXT NOT NULL,
        required_approval_level TEXT NOT NULL,
        grant_id TEXT,
        created_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS approval_requests (
        id TEXT PRIMARY KEY,
        operation_id TEXT NOT NULL,
        requested_level TEXT NOT NULL,
        status TEXT NOT NULL,
        reason TEXT NOT NULL,
        requested_by TEXT NOT NULL,
        decided_by TEXT,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        decided_at TEXT
      )`,
  `CREATE TABLE IF NOT EXISTS audit_records (
        id TEXT PRIMARY KEY,
        actor_identity TEXT NOT NULL,
        operation_id TEXT NOT NULL,
        capability_id TEXT NOT NULL,
        instruction_source TEXT NOT NULL,
        inputs_summary TEXT NOT NULL,
        outputs_summary TEXT NOT NULL,
        policy_decision_id TEXT NOT NULL,
        affected_resources_json TEXT NOT NULL,
        rollback_point_id TEXT,
        created_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS rollback_points (
        id TEXT PRIMARY KEY,
        operation_id TEXT NOT NULL,
        affected_resources_json TEXT NOT NULL,
        before_snapshot_json TEXT NOT NULL,
        after_snapshot_json TEXT NOT NULL,
        reversible INTEGER NOT NULL,
        irreversible_effects_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS artifacts (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        kind TEXT NOT NULL,
        locale TEXT NOT NULL,
        source_locales_json TEXT NOT NULL,
        file_ref_json TEXT NOT NULL,
        metadata_json TEXT NOT NULL,
        source_operation_id TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS memory_index (
        id TEXT PRIMARY KEY,
        state TEXT NOT NULL,
        topic TEXT NOT NULL,
        source TEXT NOT NULL,
        source_locale TEXT NOT NULL,
        content_locale TEXT NOT NULL,
        source_kind TEXT NOT NULL,
        instruction_authority TEXT NOT NULL,
        file_path TEXT NOT NULL,
        frontmatter_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS skill_index (
        id TEXT PRIMARY KEY,
        state TEXT NOT NULL,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        tags_json TEXT NOT NULL,
        required_capabilities_json TEXT NOT NULL,
        file_path TEXT NOT NULL UNIQUE,
        frontmatter_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS skill_usage (
        skill_id TEXT PRIMARY KEY,
        use_count INTEGER NOT NULL,
        last_used_at TEXT,
        last_run_id TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (skill_id) REFERENCES skill_index(id)
      )`,
  `CREATE TABLE IF NOT EXISTS learning_resource_uses (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        resource_kind TEXT NOT NULL,
        resource_id TEXT NOT NULL,
        resource_version TEXT,
        content_hash TEXT,
        stage TEXT NOT NULL,
        source_operation_id TEXT,
        metadata_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(run_id, resource_kind, resource_id, stage, source_operation_id),
        FOREIGN KEY (run_id) REFERENCES backend_runs(id),
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE INDEX IF NOT EXISTS learning_resource_uses_run_idx ON learning_resource_uses(run_id, created_at DESC)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS learning_resource_uses_dedupe_idx ON learning_resource_uses(run_id, resource_kind, resource_id, stage, COALESCE(source_operation_id, ''))`,
  `CREATE TABLE IF NOT EXISTS learning_evaluations (
        id TEXT PRIMARY KEY,
        learning_resource_ref_json TEXT NOT NULL,
        learning_resource_version TEXT,
        task_class TEXT NOT NULL,
        compared_run_ids_json TEXT NOT NULL,
        before_metrics_json TEXT NOT NULL,
        after_metrics_json TEXT NOT NULL,
        effect_estimate REAL NOT NULL,
        confidence REAL NOT NULL,
        assessment TEXT NOT NULL,
        evidence_refs_json TEXT NOT NULL,
        evaluator TEXT NOT NULL,
        created_at TEXT NOT NULL
      )`,
  `CREATE INDEX IF NOT EXISTS learning_evaluations_resource_idx ON learning_evaluations(learning_resource_version, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS learning_snapshots (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL,
        path TEXT NOT NULL,
        resource_counts_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        restored_at TEXT
      )`,
  `CREATE TABLE IF NOT EXISTS background_review_changes (
        id TEXT PRIMARY KEY,
        origin TEXT NOT NULL,
        source_run_id TEXT NOT NULL,
        source_session_id TEXT NOT NULL,
        review_run_id TEXT NOT NULL,
        mutation_kind TEXT NOT NULL,
        resource_ref_json TEXT NOT NULL,
        before_version TEXT,
        after_version TEXT NOT NULL,
        reason_summary TEXT NOT NULL,
        evidence_refs_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE(source_run_id, mutation_kind, after_version)
      )`,
  `CREATE TABLE IF NOT EXISTS learning_job_reports (
        id TEXT PRIMARY KEY,
        job_kind TEXT NOT NULL,
        run_id TEXT NOT NULL,
        report_json TEXT NOT NULL,
        created_at TEXT NOT NULL
      )`,
  `CREATE INDEX IF NOT EXISTS learning_job_reports_kind_idx ON learning_job_reports(job_kind, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS curator_state (
        id TEXT PRIMARY KEY,
        paused INTEGER NOT NULL,
        interval_hours INTEGER NOT NULL,
        min_idle_hours REAL NOT NULL,
        stale_after_days INTEGER NOT NULL,
        archive_after_days INTEGER NOT NULL,
        last_run_at TEXT,
        last_run_summary TEXT,
        run_count INTEGER NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS wiki_index (
        id TEXT PRIMARY KEY,
        slug TEXT NOT NULL UNIQUE,
        title TEXT NOT NULL,
        state TEXT NOT NULL,
        content_locale TEXT NOT NULL,
        tags_json TEXT NOT NULL,
        source_refs_json TEXT NOT NULL,
        provenance_json TEXT NOT NULL,
        file_path TEXT NOT NULL UNIQUE,
        frontmatter_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS collection_schemas (
        id TEXT PRIMARY KEY,
        version TEXT NOT NULL,
        file_path TEXT NOT NULL UNIQUE,
        schema_json TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS collection_records (
        id TEXT NOT NULL,
        collection_id TEXT NOT NULL,
        file_path TEXT NOT NULL UNIQUE,
        record_json TEXT NOT NULL,
        version INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        PRIMARY KEY (collection_id, id)
      )`,
  `CREATE TABLE IF NOT EXISTS collection_patches (
        id TEXT NOT NULL,
        collection_id TEXT NOT NULL,
        record_id TEXT NOT NULL,
        patch_json TEXT NOT NULL,
        source_operation_id TEXT NOT NULL,
        created_at TEXT NOT NULL,
        PRIMARY KEY (collection_id, record_id, id)
      )`,
  `CREATE TABLE IF NOT EXISTS automation_runs (
        id TEXT PRIMARY KEY,
        kind TEXT NOT NULL,
        source TEXT NOT NULL,
        session_id TEXT,
        backend_run_id TEXT,
        status TEXT NOT NULL,
        operation_id TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        error TEXT
      )`,
  `CREATE TABLE IF NOT EXISTS automation_jobs (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        kind TEXT NOT NULL,
        status TEXT NOT NULL,
        schedule TEXT NOT NULL,
        target_instruction TEXT NOT NULL,
        delivery_target_json TEXT NOT NULL,
        next_run_at TEXT,
        last_run_at TEXT,
        retry_after_at TEXT,
        locked_until TEXT,
        failure_count INTEGER NOT NULL DEFAULT 0,
        max_attempts INTEGER NOT NULL DEFAULT 3,
        last_error TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS external_sends (
        id TEXT PRIMARY KEY,
        channel TEXT NOT NULL,
        status TEXT NOT NULL,
        target_json TEXT NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        operation_id TEXT,
        approval_request_id TEXT,
        dispatch_result_json TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        dispatched_at TEXT
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_pairings (
        id TEXT PRIMARY KEY,
        channel TEXT NOT NULL,
        source_identity TEXT NOT NULL,
        source_label TEXT NOT NULL,
        status TEXT NOT NULL,
        pairing_code TEXT,
        session_key TEXT NOT NULL,
        metadata_json TEXT NOT NULL,
        requested_at TEXT NOT NULL,
        expires_at TEXT,
        resolved_at TEXT,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_pairing_policies (
        id TEXT PRIMARY KEY,
        channel TEXT NOT NULL UNIQUE,
        status TEXT NOT NULL,
        trust_mode TEXT NOT NULL,
        allowlist_json TEXT NOT NULL,
        pairing_ttl_ms INTEGER,
        duplicate_window_ms INTEGER,
        rate_limit_window_ms INTEGER,
        rate_limit_max INTEGER,
        metadata_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_routing_policies (
        id TEXT PRIMARY KEY,
        channel TEXT NOT NULL UNIQUE,
        status TEXT NOT NULL,
        session_key_strategy TEXT NOT NULL,
        default_account_id TEXT,
        default_thread_id TEXT,
        default_route TEXT NOT NULL,
        metadata_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_inbound_messages (
        id TEXT PRIMARY KEY,
        channel TEXT NOT NULL,
        source_identity TEXT NOT NULL,
        body TEXT NOT NULL,
        status TEXT NOT NULL,
        trusted INTEGER NOT NULL,
        session_key TEXT,
        pairing_id TEXT,
        message_id TEXT,
        error TEXT,
        metadata_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_boundary_policies (
        id TEXT PRIMARY KEY,
        source_channel TEXT NOT NULL,
        source_identity TEXT,
        session_key TEXT NOT NULL,
        allowed_tools_json TEXT NOT NULL,
        mcp_config_refs_json TEXT NOT NULL,
        secret_refs_json TEXT NOT NULL,
        sandbox_json TEXT NOT NULL,
        path_normalization_json TEXT NOT NULL,
        allowlist_json TEXT NOT NULL,
        timeout_ms INTEGER,
        concurrency_lock_json TEXT,
        metadata_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_mcp_configs (
        id TEXT PRIMARY KEY,
        server_name TEXT NOT NULL UNIQUE,
        transport TEXT NOT NULL,
        enabled INTEGER NOT NULL,
        allowed_tools_json TEXT NOT NULL,
        config_ref_json TEXT,
        secret_refs_json TEXT NOT NULL,
        stdio_json TEXT,
        http_json TEXT,
        metadata_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_concurrency_locks (
        id TEXT PRIMARY KEY,
        lock_key TEXT NOT NULL UNIQUE,
        scope TEXT NOT NULL,
        policy_id TEXT,
        owner_ref_json TEXT,
        status TEXT NOT NULL,
        acquired_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        released_at TEXT,
        metadata_json TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_sandbox_instances (
        id TEXT PRIMARY KEY,
        instance_key TEXT NOT NULL UNIQUE,
        scope TEXT NOT NULL,
        backend TEXT NOT NULL,
        status TEXT NOT NULL,
        sandbox_json TEXT NOT NULL,
        session_key TEXT,
        owner_ref_json TEXT,
        workspace_root TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_used_at TEXT,
        deleted_at TEXT,
        metadata_json TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS gateway_sandbox_workspace_syncs (
        id TEXT PRIMARY KEY,
        instance_id TEXT NOT NULL,
        instance_key TEXT NOT NULL,
        direction TEXT NOT NULL,
        status TEXT NOT NULL,
        workspace_root TEXT,
        remote_workspace_root TEXT,
        file_count INTEGER,
        byte_count INTEGER,
        error TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        metadata_json TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS reflection_runs (
        id TEXT PRIMARY KEY,
        kind TEXT NOT NULL,
        source_run_id TEXT,
        session_id TEXT,
        status TEXT NOT NULL,
        input_summary TEXT NOT NULL,
        output_summary TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        error TEXT
      )`,
  `CREATE TABLE IF NOT EXISTS reflection_suggestions (
        id TEXT PRIMARY KEY,
        reflection_run_id TEXT NOT NULL,
        suggestion_type TEXT NOT NULL,
        status TEXT NOT NULL,
        title TEXT NOT NULL,
        content TEXT NOT NULL,
        target_ref_json TEXT,
        source_refs_json TEXT NOT NULL,
        confidence REAL NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (reflection_run_id) REFERENCES reflection_runs(id)
      )`,
  `CREATE TABLE IF NOT EXISTS tool_runs (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        tool_call_id TEXT,
        provider_tool_name TEXT NOT NULL,
        action_id TEXT,
        status TEXT NOT NULL,
        input_summary TEXT NOT NULL,
        output_summary TEXT NOT NULL,
        resource_refs_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        FOREIGN KEY (run_id) REFERENCES backend_runs(id),
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE TABLE IF NOT EXISTS external_assist_records (
        id TEXT PRIMARY KEY,
        phase TEXT NOT NULL,
        status TEXT NOT NULL,
        provider_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        run_id TEXT,
        input_message_id TEXT,
        query TEXT NOT NULL,
        role TEXT NOT NULL,
        hints_json TEXT NOT NULL,
        error TEXT,
        isolated_from_memory INTEGER NOT NULL,
        included_in_active_memory INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (session_id) REFERENCES sessions(id),
        FOREIGN KEY (run_id) REFERENCES backend_runs(id),
        FOREIGN KEY (input_message_id) REFERENCES messages(id)
      )`,
  `CREATE TABLE IF NOT EXISTS settings (
        id TEXT PRIMARY KEY,
        ui_locale TEXT NOT NULL,
        output_locale TEXT NOT NULL,
        memory_capture_mode TEXT NOT NULL DEFAULT 'auto',
        knowledge_wiki_capture_mode TEXT NOT NULL DEFAULT 'auto',
        skill_capture_mode TEXT NOT NULL DEFAULT 'auto',
        external_provider_role TEXT NOT NULL DEFAULT 'assistive',
        default_backend_id TEXT,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS plugin_states (
        manifest_id TEXT PRIMARY KEY,
        enabled INTEGER NOT NULL,
        version TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS grants (
        id TEXT PRIMARY KEY,
        capability_id TEXT NOT NULL,
        operation TEXT NOT NULL,
        actor_identity TEXT NOT NULL,
        channel TEXT NOT NULL,
        resource_scope TEXT NOT NULL,
        manifest_version TEXT NOT NULL,
        risk_snapshot TEXT NOT NULL,
        scope_snapshot TEXT NOT NULL,
        external_impact_snapshot INTEGER NOT NULL,
        secret_requirement_snapshot TEXT NOT NULL,
        granted_by TEXT NOT NULL,
        reason TEXT NOT NULL,
        created_at TEXT NOT NULL,
        expires_at TEXT,
        revoked_at TEXT
      )`,
  `CREATE TABLE IF NOT EXISTS backend_runs (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL,
        input_message_id TEXT NOT NULL,
        output_message_id TEXT,
        backend_id TEXT NOT NULL,
        backend_kind TEXT NOT NULL,
        backend_session_id TEXT,
        status TEXT NOT NULL,
        phase TEXT,
        current_attempt INTEGER,
        request_idempotency_key TEXT,
        request_hash TEXT,
        started_at TEXT NOT NULL,
        completed_at TEXT,
        input_summary TEXT NOT NULL,
        output_summary TEXT,
        error_code TEXT,
        metadata_json TEXT NOT NULL,
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE TABLE IF NOT EXISTS backend_events (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        backend_session_id TEXT,
        event_type TEXT NOT NULL,
        sequence INTEGER NOT NULL,
        attempt_no INTEGER,
        source_event_id TEXT,
        source_sequence INTEGER,
        payload_json TEXT NOT NULL,
        resource_refs_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (run_id, sequence),
        FOREIGN KEY (run_id) REFERENCES backend_runs(id),
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE TABLE IF NOT EXISTS session_run_reservations (
        session_id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL UNIQUE,
        status TEXT NOT NULL,
        version INTEGER NOT NULL,
        held_at TEXT NOT NULL,
        released_at TEXT,
        FOREIGN KEY (session_id) REFERENCES sessions(id),
        FOREIGN KEY (run_id) REFERENCES backend_runs(id)
      )`,
  `CREATE TABLE IF NOT EXISTS client_events (
        id TEXT PRIMARY KEY,
        target_client_kind TEXT NOT NULL,
        target_client_id TEXT,
        event_type TEXT NOT NULL,
        status TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        resource_refs_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        delivered_at TEXT,
        acked_at TEXT,
        expires_at TEXT,
        error_code TEXT
      )`,
  `CREATE INDEX IF NOT EXISTS idx_client_events_delivery ON client_events(target_client_kind, status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_client_events_expiry ON client_events(status, expires_at)`,
  `CREATE TABLE IF NOT EXISTS workspace_changes (
        id TEXT PRIMARY KEY,
        run_id TEXT NOT NULL,
        session_id TEXT NOT NULL,
        resource_ref_json TEXT NOT NULL,
        change_type TEXT NOT NULL,
        summary TEXT NOT NULL,
        legacy_operation_id TEXT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (run_id) REFERENCES backend_runs(id),
        FOREIGN KEY (session_id) REFERENCES sessions(id)
      )`,
  `CREATE TABLE IF NOT EXISTS resource_translations (
        id TEXT PRIMARY KEY,
        source_ref_json TEXT NOT NULL,
        source_locale TEXT NOT NULL,
        target_locale TEXT NOT NULL,
        status TEXT NOT NULL,
        original_hash TEXT NOT NULL,
        translated_text TEXT NOT NULL,
        provenance_json TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`
] as const;

export const coreBaselineMigration: WorkspaceMigration = {
  version: 1,
  name: "core_baseline",
  steps: statements.map((statement) => ({ kind: "sql" as const, statement }))
};

export const coreBaselineChecksum = "718605c93db76d3548d493701b1130b9d0e19d1d02240a02e3dfa069f4f5f539";
