import type { CapabilityManifest } from "@samurai-agent/core-schemas";

export const proposalCapabilityManifest: CapabilityManifest = {
  id: "proposal_workspace",
  version: "1.1.0",
  title: "Workspace proposal capability",
  description: "Creates local drafts, provisional memory, and approval-gated outbound actions.",
  operations: [
    {
      operation: "file.read",
      description: "Read a file inside the local workspace.",
      input_schema_ref: "file.read.input",
      output_schema_ref: "file.read.output",
      risk: "low",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning", "scheduled_context"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "file.list",
      description: "List files inside the local workspace.",
      input_schema_ref: "file.list.input",
      output_schema_ref: "file.list.output",
      risk: "low",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning", "scheduled_context"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "file.inspect",
      description: "Inspect file metadata and related Workspace provenance.",
      input_schema_ref: "file.inspect.input",
      output_schema_ref: "file.inspect.output",
      risk: "low",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning", "scheduled_context"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "file.write",
      description: "Write a file inside the local workspace.",
      input_schema_ref: "file.write.input",
      output_schema_ref: "file.write.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "file.patch",
      description: "Patch a file inside the local workspace.",
      input_schema_ref: "file.patch.input",
      output_schema_ref: "file.patch.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "rollback.restore",
      description: "Restore a reversible local workspace snapshot from a rollback point.",
      input_schema_ref: "rollback.restore.input",
      output_schema_ref: "rollback.restore.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "browser.navigate",
      description: "Navigate or fetch a browser-readable page for workspace use.",
      input_schema_ref: "browser.navigate.input",
      output_schema_ref: "browser.navigate.output",
      risk: "medium",
      scope: "external_channel",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "browser.extract",
      description: "Extract text from a browser-readable page.",
      input_schema_ref: "browser.extract.input",
      output_schema_ref: "browser.extract.output",
      risk: "medium",
      scope: "external_channel",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "browser.screenshot",
      description: "Capture a browser screenshot into the workspace when an adapter is configured.",
      input_schema_ref: "browser.screenshot.input",
      output_schema_ref: "browser.screenshot.output",
      risk: "medium",
      scope: "external_channel",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "browser.interact",
      description: "Perform a browser interaction that may submit data or trigger an external side effect through a configured adapter.",
      input_schema_ref: "browser.interact.input",
      output_schema_ref: "browser.interact.output",
      risk: "high",
      scope: "external_channel",
      reversibility: false,
      external_impact: true,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "requires_approval"
    },
    {
      operation: "browser.download_to_workspace",
      description: "Download browser-readable content into the local workspace.",
      input_schema_ref: "browser.download_to_workspace.input",
      output_schema_ref: "browser.download_to_workspace.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "external.send.prepare",
      description: "Prepare an outbound send draft without dispatching it.",
      input_schema_ref: "external.send.prepare.input",
      output_schema_ref: "external.send.prepare.output",
      risk: "medium",
      scope: "external_channel",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "external.send.dispatch",
      description: "Dispatch a prepared outbound send after approval.",
      input_schema_ref: "external.send.dispatch.input",
      output_schema_ref: "external.send.dispatch.output",
      risk: "high",
      scope: "external_channel",
      reversibility: false,
      external_impact: true,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "requires_approval"
    },
    {
      operation: "automation.job.save",
      description: "Save an automation job definition.",
      input_schema_ref: "automation.job.save.input",
      output_schema_ref: "automation.job.save.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "automation.job.run",
      description: "Run an enabled automation job through scheduled context.",
      input_schema_ref: "automation.job.run.input",
      output_schema_ref: "automation.job.run.output",
      risk: "low",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["scheduled_context"],
      default_decision: "allow_auto"
    },
    {
      operation: "reflection.suggestion.apply",
      description: "Apply a reflection suggestion to Memory, Knowledge Wiki, or Skill candidates.",
      input_schema_ref: "reflection.suggestion.apply.input",
      output_schema_ref: "reflection.suggestion.apply.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "artifact.create",
      description: "Create a local markdown artifact draft.",
      input_schema_ref: "artifact.create.input",
      output_schema_ref: "artifact.create.output",
      risk: "low",
      scope: "artifact",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning", "scheduled_context"],
      default_decision: "allow_auto"
    },
    {
      operation: "artifact.revise",
      description: "Create an immutable revision of a local Artifact.",
      input_schema_ref: "artifact.revise.input",
      output_schema_ref: "artifact.revise.output",
      risk: "low",
      scope: "artifact",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "artifact.repair",
      description: "Restore a missing Artifact revision file from its verified local blob.",
      input_schema_ref: "artifact.repair.input",
      output_schema_ref: "artifact.repair.output",
      risk: "low",
      scope: "artifact",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "scheduled_context"],
      default_decision: "allow_with_audit"
    },
    ...["artifact.restore_revision", "artifact.export_pdf", "graph.create", "graph.patch", "image.generate", "image.edit", "skill.patch", "automation.job.set_status"].map((operation): CapabilityManifest["operations"][number] => ({
      operation,
      description: `Run the ${operation} Artifact operation through the Runtime boundary.`,
      input_schema_ref: `${operation}.input`,
      output_schema_ref: `${operation}.output`,
      risk: "low",
      scope: "artifact",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning"],
      default_decision: "allow_with_audit"
    })),
    {
      operation: "memory.session.create",
      description: "Keep a session-scoped memory note.",
      input_schema_ref: "memory.session.create.input",
      output_schema_ref: "memory.session.create.output",
      risk: "low",
      scope: "memory",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "agent_reasoning", "scheduled_context"],
      default_decision: "allow_auto"
    },
    {
      operation: "memory.topic.create",
      description: "Create a non-sensitive topic memory candidate.",
      input_schema_ref: "memory.topic.create.input",
      output_schema_ref: "memory.topic.create.output",
      risk: "medium",
      scope: "memory",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "memory.archive",
      description: "Archive a memory item so it leaves normal memory views without deleting the record.",
      input_schema_ref: "memory.archive.input",
      output_schema_ref: "memory.archive.output",
      risk: "medium",
      scope: "memory",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "skill.view",
      description: "Read a selected Skill body or declared support file on demand.",
      input_schema_ref: "skill.view.input",
      output_schema_ref: "skill.view.output",
      risk: "low",
      scope: "skill",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "agent_reasoning"],
      default_decision: "allow_auto"
    },
    {
      operation: "skill.candidate.create",
      description: "Create a local skill candidate markdown file.",
      input_schema_ref: "skill.candidate.create.input",
      output_schema_ref: "skill.candidate.create.output",
      risk: "low",
      scope: "skill",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "agent_reasoning"],
      default_decision: "allow_auto"
    },
    {
      operation: "skill.project.save",
      description: "Save a promoted project skill markdown file.",
      input_schema_ref: "skill.project.save.input",
      output_schema_ref: "skill.project.save.output",
      risk: "medium",
      scope: "skill",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "skill.support_file.save",
      description: "Save a support file for a local Skill.",
      input_schema_ref: "skill.support_file.save.input",
      output_schema_ref: "skill.support_file.save.output",
      risk: "medium",
      scope: "skill",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy", "agent_reasoning"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "skill.lifecycle.apply",
      description: "Apply a curator lifecycle transition to a local Skill without deleting its markdown.",
      input_schema_ref: "skill.lifecycle.apply.input",
      output_schema_ref: "skill.lifecycle.apply.output",
      risk: "medium",
      scope: "skill",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "wiki.proposal.create",
      description: "Create a proposed knowledge wiki markdown page.",
      input_schema_ref: "wiki.proposal.create.input",
      output_schema_ref: "wiki.proposal.create.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "agent_reasoning"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "wiki.accept",
      description: "Accept a proposed knowledge wiki page for active retrieval.",
      input_schema_ref: "wiki.accept.input",
      output_schema_ref: "wiki.accept.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "wiki.reject",
      description: "Reject a proposed knowledge wiki page without deleting its markdown.",
      input_schema_ref: "wiki.reject.input",
      output_schema_ref: "wiki.reject.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "wiki.patch",
      description: "Edit knowledge wiki frontmatter or markdown content.",
      input_schema_ref: "wiki.patch.input",
      output_schema_ref: "wiki.patch.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "wiki.archive",
      description: "Archive a knowledge wiki page without deleting its markdown.",
      input_schema_ref: "wiki.archive.input",
      output_schema_ref: "wiki.archive.output",
      risk: "medium",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "wiki.reindex",
      description: "Refresh the knowledge wiki SQLite index from markdown pages.",
      input_schema_ref: "wiki.reindex.input",
      output_schema_ref: "wiki.reindex.output",
      risk: "low",
      scope: "workspace",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "scheduled_context"],
      default_decision: "allow_auto"
    },
    {
      operation: "collection.schema.save",
      description: "Save a collection schema to the local workspace.",
      input_schema_ref: "collection.schema.save.input",
      output_schema_ref: "collection.schema.save.output",
      risk: "medium",
      scope: "collection",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "collection.record.create",
      description: "Create a local collection record.",
      input_schema_ref: "collection.record.create.input",
      output_schema_ref: "collection.record.create.output",
      risk: "medium",
      scope: "collection",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "collection.patch.apply",
      description: "Apply a local collection record patch.",
      input_schema_ref: "collection.patch.apply.input",
      output_schema_ref: "collection.patch.apply.output",
      risk: "medium",
      scope: "collection",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "collection.record.delete",
      description: "Delete a local collection record through runtime permission checks.",
      input_schema_ref: "collection.record.delete.input",
      output_schema_ref: "collection.record.delete.output",
      risk: "medium",
      scope: "collection",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "collection.manage",
      description: "Read or write Collection items and schemas through the shared Collection management surface.",
      input_schema_ref: "collection.manage.input",
      output_schema_ref: "collection.manage.output",
      risk: "medium",
      scope: "collection",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "scheduled_context"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "collection.action.run",
      description: "Run a collection-defined local action through the runtime policy boundary.",
      input_schema_ref: "collection.action.run.input",
      output_schema_ref: "collection.action.run.output",
      risk: "medium",
      scope: "collection",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "scheduled_context"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "collection.reindex",
      description: "Refresh collection SQLite indexes from schema and record files.",
      input_schema_ref: "collection.reindex.input",
      output_schema_ref: "collection.reindex.output",
      risk: "low",
      scope: "collection",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "scheduled_context"],
      default_decision: "allow_auto"
    },
    {
      operation: "grant.create",
      description: "Create an owner-scoped grant for a capability operation.",
      input_schema_ref: "grant.create.input",
      output_schema_ref: "grant.create.output",
      risk: "medium",
      scope: "identity",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "grant.revoke",
      description: "Revoke an existing capability grant.",
      input_schema_ref: "grant.revoke.input",
      output_schema_ref: "grant.revoke.output",
      risk: "medium",
      scope: "identity",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "allow_with_audit"
    },
    {
      operation: "automation.memory_review.run",
      description: "Run the minimal scheduled memory review automation.",
      input_schema_ref: "automation.memory_review.run.input",
      output_schema_ref: "automation.memory_review.run.output",
      risk: "low",
      scope: "memory",
      reversibility: true,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["scheduled_context"],
      default_decision: "allow_auto"
    },
    {
      operation: "external.send",
      description: "Prepare an outbound send operation.",
      input_schema_ref: "external.send.input",
      output_schema_ref: "external.send.output",
      risk: "high",
      scope: "external_channel",
      reversibility: false,
      external_impact: true,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction", "owner_approved_policy"],
      default_decision: "requires_approval"
    },
    {
      operation: "workspace.delete",
      description: "Delete a workspace resource.",
      input_schema_ref: "workspace.delete.input",
      output_schema_ref: "workspace.delete.output",
      risk: "irreversible",
      scope: "workspace",
      reversibility: false,
      external_impact: false,
      secret_requirement: "none",
      allowed_instruction_sources: ["owner_instruction"],
      default_decision: "requires_strong_approval"
    }
  ],
  input_schema: {},
  output_schema: {},
  ui_surfaces: ["chat", "artifact", "context_drawer", "audit"],
  agent_tools: [
    "artifact.create",
    "generated_surface.create",
    "generated_surface.revise",
    "artifact.revise",
    "artifact.repair",
    "artifact.restore_revision",
    "artifact.export_pdf",
    "graph.create",
    "graph.patch",
    "image.generate",
    "image.edit",
    "skill.patch",
    "automation.job.set_status",
    "file.read",
    "file.inspect",
    "file.list",
    "file.write",
    "file.patch",
    "rollback.restore",
    "browser.navigate",
    "browser.extract",
    "browser.interact",
    "browser.screenshot",
    "browser.download_to_workspace",
    "memory.session.create",
    "memory.topic.create",
    "memory.archive",
    "skill.view",
    "skill.candidate.create",
    "skill.project.save",
    "skill.support_file.save",
    "skill.lifecycle.apply",
    "wiki.proposal.create",
    "wiki.accept",
    "wiki.reject",
    "wiki.patch",
    "wiki.archive",
    "wiki.reindex",
    "collection.schema.save",
    "collection.record.create",
    "collection.patch.apply",
    "collection.record.delete",
    "collection.manage",
    "collection.action.run",
    "collection.reindex",
    "automation.memory_review.run",
    "automation.job.save",
    "automation.job.run",
    "reflection.suggestion.apply",
    "external.send.prepare",
    "external.send.dispatch",
    "external.send",
    "workspace.delete"
  ],
  permission_policy: {
    grant_key: "capability_id+operation+actor_identity+channel+resource_scope"
  },
  secret_policy: {
    direct_secret_values: false
  },
  audit_policy: {
    state_changes: "always"
  },
  rollback_policy: {
    workspace_changes: "snapshot"
  }
};

export const capabilityManifests = [proposalCapabilityManifest] as const;

export function getCapabilityManifest(capabilityId: string): CapabilityManifest | undefined {
  return capabilityManifests.find((manifest) => manifest.id === capabilityId);
}
