import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { isIP } from "node:net";

export class OwnerTokenManager {private current:string;private previous?:{hash:string;expiresAt:number};constructor(token:string,private readonly graceMs=30000){if(token.length<32)throw new Error("owner_token_too_short");this.current=hash(token)}verify(token:string|undefined,now=Date.now()){if(!token)return false;const candidate=hash(token);return equal(candidate,this.current)||Boolean(this.previous&&now<=this.previous.expiresAt&&equal(candidate,this.previous.hash))}rotate(nextToken:string,now=Date.now()){if(nextToken.length<32)throw new Error("owner_token_too_short");this.previous={hash:this.current,expiresAt:now+this.graceMs};this.current=hash(nextToken)}}
export class SlidingWindowRateLimiter {private readonly hits=new Map<string,number[]>();constructor(private readonly max:number,private readonly windowMs:number){}allow(key:string,now=Date.now()){const active=(this.hits.get(key)??[]).filter(at=>at>now-this.windowMs);if(active.length>=this.max){this.hits.set(key,active);return false}active.push(now);this.hits.set(key,active);return true}}
export function isAllowedCorsOrigin(origin:string|undefined,allowlist:string[]){if(!origin)return true;return allowlist.includes(origin)}
export function assertRequestSize(contentLength:string|undefined,maxBytes:number){if(contentLength&&Number(contentLength)>maxBytes)throw new Error("request_body_too_large")}
export async function validateOutboundHttpUrl(raw:string,resolve:(hostname:string)=>Promise<string[]>):Promise<URL>{const url=new URL(raw);if(!["http:","https:"].includes(url.protocol)||url.username||url.password)throw new Error("outbound_url_invalid");const addresses=isIP(url.hostname)?[url.hostname]:await resolve(url.hostname);if(addresses.length===0||addresses.some(isPrivateAddress))throw new Error("outbound_url_private_address");return url}
export function redactSecurityValue(value:unknown,key=""):unknown{if(/secret|token|api[_-]?key|password|credential|authorization|cookie/i.test(key))return"[redacted]";if(typeof value==="string")return value.replace(/Bearer\s+\S+/gi,"Bearer [redacted]").replace(/(token|secret|password|api[_-]?key)\s*[:=]\s*\S+/gi,"$1=[redacted]");if(Array.isArray(value))return value.map(x=>redactSecurityValue(x));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,redactSecurityValue(v,k)]));return value}
export function evaluateApiAccess(input:{path:string;ip:string;token?:string;contentLength?:string;now?:number},policy:{owner?:OwnerTokenManager;rate:SlidingWindowRateLimiter;maxBodyBytes:number}){try{assertRequestSize(input.contentLength,policy.maxBodyBytes);if(!policy.rate.allow(input.ip,input.now))return{allowed:false,status:429,error:"rate_limited"};const signedWebhook=/^\/gateway\/(?:webhooks\/|slack\/events|telegram\/events|line\/events|email\/provider-webhooks\/)/.test(input.path);if(!policy.owner||input.path==="/health"||signedWebhook)return{allowed:true,status:200};return policy.owner.verify(input.token,input.now)?{allowed:true,status:200}:{allowed:false,status:401,error:"owner_token_invalid"}}catch(error){return{allowed:false,status:413,error:error instanceof Error?error.message:"request_rejected"}}}
export function verifySignedWebhook(input:{secret:string;timestamp:string;signature:string;body:Uint8Array;now?:number;maxSkewSeconds?:number}){const timestamp=Number(input.timestamp),now=Math.floor((input.now??Date.now())/1000);if(!Number.isFinite(timestamp)||Math.abs(now-timestamp)>(input.maxSkewSeconds??300))return{ok:false,reason:"timestamp_out_of_range"};const expected=createHmac("sha256",input.secret).update(`${input.timestamp}.`).update(input.body).digest("hex");return{ok:equal(Buffer.from(expected),Buffer.from(input.signature.toLowerCase())),reason:equal(Buffer.from(expected),Buffer.from(input.signature.toLowerCase()))?undefined:"signature_invalid"}}
function hash(value:string){return createHash("sha256").update(value).digest()}function equal(a:Buffer,b:Buffer){return a.length===b.length&&timingSafeEqual(a,b)}
function isPrivateAddress(address:string){const normalized=address.toLowerCase();if(normalized==="::1"||normalized==="::"||normalized.startsWith("fe80:")||normalized.startsWith("fc")||normalized.startsWith("fd"))return true;if(normalized.startsWith("::ffff:"))return isPrivateAddress(normalized.slice(7));const parts=normalized.split(".").map(Number);if(parts.length!==4||parts.some(x=>!Number.isInteger(x)||x<0||x>255))return true;const a=parts[0]!,b=parts[1]!;return a===0||a===10||a===127||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a>=224}
